### ISSUE TITLE
Add new rule

### ISSUE THREAD

**Issue by hungbang** [kiegroup/optaweb-employee-rostering#392] opened 2020-02-19 03:00 UTC
I am trying to add new rule to `optaweb-employee-rostering`, in which, I've added a `requiredSkillSet` to `ShiftTemplate` :
```
    @NotNull
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "ShiftTemplateRequiredSkillSet",
            joinColumns = @JoinColumn(name = "shiftTemplateId", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "skillId", referencedColumnName = "id")
    )
    private Set<Skill> requiredSkillSet;
```

The rule that I want to define is:
Condition: Employee has `requiredSkillSet` would be assigned to Shift. 
Actually, I am a new Opta(just 2 days of research and modifying this example), so Does anyone can help me to create the rule above? Thank you in advance.

**Comment by Christopher-Chianelli** [comment] 2020-02-19 04:36
`requiredSkillSet` is a property of Spots, and is a built-in constraint (https://github.com/kiegroup/optaweb-employee-rostering/blob/9a561b7db5510774ad2ddf777fab3a34f40abba5/optaweb-employee-rostering-backend/src/main/resources/org/optaweb/employeerostering/service/solver/employeeRosteringScoreRules.drl#L42-L49).

Every `Shift` has a `Spot` and inherits the `Spot`'s `requiredSkillSet` (https://github.com/kiegroup/optaweb-employee-rostering/blob/9a561b7db5510774ad2ddf777fab3a34f40abba5/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/spot/Spot.java#L45-L51). Similarly, every `ShiftTemplate` has a `Spot` and the `Shifts` created from that `ShiftTemplate` inherits its Spot (and thus the `Spot`'s skill set).

To help explain the domain of this project:

- `Skill` is an attribute an employee may be proficient in and a spot may require.
- `Spot` is a position/location (location for security guards, department for nurse rostering, region for call centers, etc.) and each spot may require different skill sets (for instance, an Employee need to be able to speak English to fill the North America spot for call centers, and need to speak Spanish to fill the Latin America spot).
- `Shift` is an position that needs to be filled for a given spot at a given time.
- `ShiftTemplate` is a Shift without a date and time, and instead has a rotation offset which is used to determine when to create its shift(s).

What are you trying to achieve, exactly (that is, why are you adding `requiredSkillSet` to `ShiftTemplate`, given that it is a property of `Spot`)?

**Comment by miyamoza** [comment] 2020-02-19 04:57
I guess the use case would be for a certain shift that requires a skill.
Spot may be a position/ location, but from the skill point of view will be uniform. Everybody in that spot will have the same skill(s).

What if, for the same spot there is a need between 8:00 ~ 12:00 for 3 shifts with Skill A, Skill B and Skill C (as a team kind of thing that complements each-other)!!!

**Comment by hungbang** [comment] 2020-02-19 05:27
Thank you for your answer @Christopher-Chianelli , @miyamoza , actually the user case is the Shift should be assigned either by Rotation Employee or Rotation Skill is defined in the ShiftTemplate. 

For example:

1. Creates 2 skills: A, B
2. Creates Contract by Default
3. Creates 4 Employees: 1 with Skill A, 2 with skill A, 3 with skill B, 4 with skill B
4. Creates Spot team A
5. Creates rotation shift:
Day 1/1: 7:00 ~ 16:00 (skill A)
Day 1/1: 7:00 ~ 16:00 (skill B)
Day 1/2: 16:00 ~ 7:00 (skill A)
Day 1/2: 16:00 ~ 7:00 (skill B)

6. Publish
7. Schedule 

8 Result:
Employee 1 & 2 are paired in Day 1/1 (Skill A & Skill A)
Employee 3 & 4 are paired in Day 1/2 (Skill B & Skill B)

----------------
expected result:
Employee 1 & 3 paired in Day 1/1 (skill A & skill B)
Employee 2 & 4 paired in Day 1/2 (skill A & skill B)

That's why I want to add a new rule to assign the employee who has the rotation skill to the shift.

**Comment by hungbang** [comment] 2020-02-19 07:04
@Christopher-Chianelli I hope that you read the example above, please don't hesitate to correct me if I wrong.

**Comment by Christopher-Chianelli** [comment] 2020-02-19 14:52
@hungbang is there anything preventing you from using two Spots?

1. Creates 2 skills: A, B

2. Creates Contract by Default

3. Creates 4 Employees: 1 with Skill A, 2 with skill A, 3 with skill B, 4 with skill B

4. Creates Spots A (with required skill set {A}), B (with required skill set {B})

5. Creates rotation shift:
    Day 1/1: 7:00 ~ 16:00 (Spot A)
    Day 1/1: 7:00 ~ 16:00 (Spot B)
    Day 1/2: 16:00 ~ 7:00 (Spot A)
    Day 1/2: 16:00 ~ 7:00 (Spot B)

6. Publish

7. Schedule

If not, can you explain your use case to help me understand?

**Comment by hungbang** [comment] 2020-02-19 16:00
Thank you for your suggestion, I will try with it.
The use case is we will have only one spot and the guys belong to the spot with his skills. 
the idea is that I want to pair a person with skill A with a person with skill B for example on Day 1 of the shift template

**Comment by hungbang** [comment] 2020-02-20 01:39
@Christopher-Chianelli @miyamoza 

This kind of layout would be useful for periodic maintenance crews of complex systems, when employees with complementary skills are required in the same shift. (cross functional shifts)
--
Different teams will be formed in order to satisfy different customers/different systems/different locations
In the shift template, being able to define either the rotational employee, or the skill or nothing, would cover the use case above
So assignment to the shift should also be based on the skill required for the shift
 
If we map a skill to a spot, that spot becomes uniform, it will have only that skill (this in itself is not a bad thing if the requirement is to have the same skills)
We need to map a skill to a shift in order to create teams in a time-range that have employees with complementary skills
Employee E4 can be assigned to any of the shifts that have a common subset of skills with the required shift skill (in this case, E1 can do both S1 & S2, so it can fill any of the shifts)
 
the way the optaroster works now, if we assign S1 & S2 to a spot, only employees that `containsAll` skills will be assigned to the shifts of that spot (for example only E4)

So that's why we need to create shift assignments for employees with complementary skills.

**Comment by miyamoza** [comment] 2020-02-20 02:15
@hungbang 

can you please add what E1, S1, S2 represents?

**Comment by hungbang** [comment] 2020-02-20 04:39
@miyamoza E1 : employee 1

S1, S2: skill 1, skill 2

**Comment by hungbang** [comment] 2020-02-20 04:49
`

3 teams | - team T1 |   |   |  
-- | -- | -- | -- | --
  | - team T2 |   |   |  
  | - team T3 |   |   |  
  |   |   |   |  
2 skills | - skill S1 |   |   |  
  | - skill S2 |   |   |  
  |   |   |   |  
several employees | - employee E1 | - having only skill S1 |   |  
  | - employee E2 | - having only skill S1 |   |  
  | - employee E3 | - having only skill S2 |   |  
  | - employee E4 | - having skill S1, S2 |   |  
  | : | : |   |  
  | - employee En | - having only skill S1 |   |  
  |   |   |   |  
rotation shift for T1 | Day 1 | Day 2
  | 08:00 ~ 14:00 | S1 | 08:00 ~ 16:00 | E2
  | 08:00 ~ 14:00 | S2 | 08:00 ~ 16:00 | E3
  | 14:00 ~ 20:00 | E1 | 16:00 ~ 23:00 | S1
  | 14:00 ~ 20:00 | S2 | 16:00 ~ 23:00 | S2
  | 20:00 ~ 08:00 | S1 | 16:00 ~ 23:00 | S2
  | 20:00 ~ 08:00 | S1 | 23:00 ~ 08:00 | E1
  | 20:00 ~ 08:00 | E2 | 23:00 ~ 08:00 | S2
  |   |   |   |  
rotation shift for T2 | - something similar with the above |   |   |  
  | - ability to define a required skill for a rotational shift |   |   |  
  | - keep the functionality of defining a preffered employee for a rotational shift |   |   |  
  | - create shift assignments for employees with complementary skills |   |   |  

`

**Comment by Christopher-Chianelli** [comment] 2020-02-24 20:41
To implement this rule, you will also need to add `requiredSkillSet` to `Shift`, and update `ShiftTemplate.createShiftOnDate` to set the `requiredSkillSet` on the `Shift`. Then you need to update `Employee.hasSkills` to take two parameters (one for the Spot required skill set, another for the Shift required skill set) and make it return true iff the employee has all the skills in both skill sets. Finally, you need to modify the rule "Required skill for a shift" in `employeeRosteringScoreRules.drl` to pass in both parameters to  `getEmployee().hasSkills`.

Just a word of caution for this approach: it will become hard to visualize groups of complementary shifts in the UI. I recommend adding a new Domain Object for this purpose (it will basically be identical to Spot).

**Comment by hungbang** [comment] 2020-02-26 10:10
Hi @Christopher-Chianelli , thank you for your solution. I did it, but I am not sure why I got null`rotationSkill` in rule `Required skill for a shift`:
```
rule "Required skill for a shift"
    when
        Shift(
                employee != null,
                !getEmployee().hasSkills(getSpot().getRequiredSkillSet(), getRotationSkill()))
    then
        scoreHolder.addHardConstraintMatch(kcontext, -100);
end
```

in the ShiftRepository:
```
@Query("select distinct sa from Shift sa" +
            " left join fetch sa.spot s" +
            " left join fetch sa.rotationEmployee re" +
            " left join fetch sa.employee e" +
            " left join fetch sa.rotationSkill rs" +
            " where sa.tenantId = :tenantId" +
            " order by sa.startDateTime, s.name, e.name")
    List<Shift> findAllByTenantId(@Param("tenantId") Integer tenantId);
```

after run api: `/publishAndProvision`, the shift table would be :
![image](https://user-images.githubusercontent.com/10163092/75334638-c9bd2900-58ba-11ea-866d-258c6b559b23.png)

**Comment by hungbang** [comment] 2020-02-26 14:36
There is a bug here: 
`skillProficiencySet.containsAll(skills)` would return `true` if  the `skills` is empty.

**Comment by Christopher-Chianelli** [comment] 2020-02-26 14:44
@hungbang that not a bug; `skillProficiencySet` is the Employee's skills, `skills` are the Spot's `skills`. So `skillProficiencySet.containsAll(skills)` reads "The Spot skills are a subset of the Employee's Skills" (i.e. the Employee has all the skills required for the Spot".

**Comment by Christopher-Chianelli** [comment] 2020-02-26 14:51
What is probably a bug is using "or" instead of "and"; Say `Spot A` requires a "HR" skill, and `Shift 1` rotation skill is "Accounting". Then an Employee that has only "HR" can be assigned to Shift 1, and and Employee that has only "Accounting" can be assigned to Shift 1. What you probably want is an Employee that has both "HR" and "Accounting". (Other word of caution: right now there is an assumption every Shift has a Rotation Skill, if at any point of time Rotation Skill becomes optional, the code would break; you would need a null check, use Optional<Skill>, or use Collection<Skill>).

**Comment by hungbang** [comment] 2020-02-26 14:51
yes, I see. But for an example:
`skillProficiencySet `: [skill a]
`skills`: []

as I understand the expression should return false because there is no skill from spot exists in `skillProficiencySet `.

**Comment by Christopher-Chianelli** [comment] 2020-02-26 15:00
I think we have different ideas of what constraint should do.
Mine:
`∀s(s is Shift => ∀x(x in s.spot.requiredSkillSet => x in s.employee.skillProficiencySet))`
(or, in English: For each shift, every skill in the Shift's Spot's requiredSkillSet is also in the Shift's employee's skillProficiencySet)
Yours (probably):
`∀s(s is Shift => ∃x(x in s.spot.requiredSkillSet and x in s.employee.skillProficiencySet))`
(or, in English: For each shift, a skill in the Shift's Spot's requiredSkillSet is in the Shift's employee's skillProficiencySet)

**Comment by hungbang** [comment] 2020-02-26 15:09
Totally agree with you. just what I want to say: we should check the spot.skills.isEmpty first. 
I tried a test case: 
- Creates a spot with no skill
- Creates an employee with skillProficiencySet = [`skill a`]

then
`skillProficiencySet.containsAll(skills) = true`

Expected result: `skillProficiencySet.contains(skills) = false` 

Correct me if I wrong. Thank you @Christopher-Chianelli

**Comment by Christopher-Chianelli** [comment] 2020-02-26 15:17
Expected is `skillProficiencySet.containsAll(skills) = true`. For all x is true on **all** empty datasets (unlike there exists, which requires the dataset to not be empty). This case occurs when no special skills are required for a Spot, so any Employee can do it.

**Comment by hungbang** [comment] 2020-02-26 15:19
great. it makes sense Thank you @Christopher-Chianelli

**Closed** 2022-07-21 09:56 UTC
