### ISSUE TITLE
Rotation screen: If I click a employee stub, but drag it too fast on TimeBucket, I will report an error

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#489] opened 2020-08-19 02:09 UTC
![1](https://user-images.githubusercontent.com/56569509/90583920-ec921f80-e203-11ea-8a3a-44636f26b9c8.png)

The backend error log is:
2020-08-19 09:56:45.180  WARN 4664 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]
2020-08-19 09:56:45.180  WARN 4664 --- [nio-8080-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]
2020-08-19 09:56:45.180  WARN 4664 --- [nio-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]
2020-08-19 09:56:45.181  WARN 4664 --- [io-8080-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]
2020-08-19 09:56:45.192  WARN 4664 --- [nio-8080-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]
2020-08-19 09:56:45.231  WARN 4664 --- [nio-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved 

[org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [org.optaweb.employeerostering.domain.rotation.TimeBucket] 

with identifier [117]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by 

another transaction (or unsaved-value mapping was incorrect) : [org.optaweb.employeerostering.domain.rotation.TimeBucket#117]]

**Comment by Christopher-Chianelli** [comment] 2020-08-19 03:39
That error is caused by sending concurrent REST requests via mouse drag. Tracker JIRA is PLANNER-2105 (https://issues.redhat.com/browse/PLANNER-2105). To fix, we would need to limit the requests sent, either sending them in bulk on mouse release or via a timer.

**Comment by Christopher-Chianelli** [comment] 2020-08-19 03:39
(Note: this error doesn't actually cause any problems; any updates are still saved.)

**Comment by JiangWeian** [comment] 2020-08-19 05:36
@Christopher-Chianelli , If it doesn't cause an error, I don't think this kind of error will appear on the page. The prompt on the page should be filtered out.

**Comment by triceo** [comment] 2020-08-19 06:18
I actually ran into the same thing. I agree - if it's not an issue, it shouldn't throw errors.

**Comment by Christopher-Chianelli** [comment] 2020-09-09 20:33
Fixed by https://github.com/kiegroup/optaweb-employee-rostering/pull/481

**Closed by Christopher-Chianelli** 2020-09-09 20:33 UTC
