### ISSUE TITLE
Adding more constraints to rostering example

### ISSUE THREAD

**Issue by liviu-andrei-ioan** [kiegroup/optaweb-employee-rostering#455] opened 2020-06-25 14:38 UTC
Hello, guys,

I'm very happy I found optaplanner; good job.
I am trying to implement a roster for my wife's doctors team using the rostering project example.
I wrote a small Java client that creates a Tenant with Skills, Spots, Contracts, Employees (doctors) and Shifts (one for each day of the month).

I am interested in adding new constraints, especially a "minimum number of minutes per month" condition in the Contract.
(all doctors must be assigned at least one shift, and now some are left with 0 shifts assigned; of course, ideally, all doctors should be assigned the same "fair" number of shifts)

Actually, I would be interested in all of the soft constraints presented in the [manual](https://docs.optaplanner.org/7.38.0.Final/optaplanner-docs/html_single/index.html#nurseRosteringProblemDescription
)

Q1: Could you guys give me some pointers in adding the "minimum number of minutes per month" constraint?
I looked into the code and this place seems a good starting point:
optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java
```java
@Override
public Constraint[] defineConstraints(ConstraintFactory constraintFactory) {
    return new Constraint[]{
            requiredSkillForShift(constraintFactory),
            unavailableEmployeeTimeSlot(constraintFactory),
            noOverlappingShifts(constraintFactory),
            noMoreThanTwoConsecutiveShifts(constraintFactory),
            breakBetweenNonConsecutiveShiftsIsAtLeastTenHours(constraintFactory),
            dailyMinutesMustNotExceedContractMaximum(constraintFactory),
            weeklyMinutesMustNotExceedContractMaximum(constraintFactory),
            monthlyMinutesMustNotExceedContractMaximum(constraintFactory),
            yearlyMinutesMustNotExceedContractMaximum(constraintFactory),
            assignEveryShift(constraintFactory),
            employeeIsNotOriginalEmployee(constraintFactory),
            undesiredEmployeeTimeSlot(constraintFactory),
            desiredEmployeeTimeSlot(constraintFactory),
            employeeNotRotationEmployee(constraintFactory)
    };
}
```
Q2: Do you plan to add the soft constraints from the manual in the roster example?

Thank you.
Regards,
Liviu

**Comment by liviu-andrei-ioan** [comment] 2020-07-01 06:35
Hello again,

I finished my Java client app that inserts data into the optaplanner standalone service and then collects the result, generating a table in a PDF. I made multiple tests and I was able to understand what optaplanner had generated.

Q3: Can HARD constraints also be broken? If HARD constraints get broken, does it mean:
i) that optaplanner was not able to find a solution under the current constraints?
or 
ii) that a solution simply _does not exist_ under the current constraints?
Q3 a): Why do I get unassigned shifts, if people are still available?
Q3 b): I manually assigned an employee to a shift (pinned), and optaplanner added another employee on that shift, so 2 employees now have the same shift.

Q4: Because the total time constraint is per week, people sometimes receive shifts on weekends, and then on Monday.
Q4 a): Any tips on how to add spacing between shifts?
Q4 b): Any tips on how to limit the number of Saturdays/Sundays worked per month?

I am interested in raising the quality of my solutions.
Now, I am unable to make good use of the solutions generated by optaplanner (because of the above stated reasons).

Optaplanner indeed generates solutions very quickly (1 minute for 40 employees and 2 contracts).
I would prefer to wait more and be able to increase the quality of the solutions.

Thank you for your help.
Regards,
Liviu

**Comment by Christopher-Chianelli** [comment] 2020-07-01 19:27
Greetings,

Q1: The minimum hours per week is similar to the maximum hours per week constraint; it would look like this in the
constraint provider: https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java#L171-L186, except using the minimum hours of the Contract object, and changing the ">" to a "<" in the final filter. I know there are some performance regressions right now for the Java Constraint Provider compared to the Drools file (the Drools version of the constraint is here: https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/resources/org/optaweb/employeerostering/service/solver/employeeRosteringScoreRules.drl#L131-L148), so if you are using this, I recommend modifying the Drools file to add the minimum minutes constraint
(change `Number(this > $contract.getMaximumMinutesPerWeek()) from $totalMinutes` to `Number(this < $contract.getMinimumMinutesPerWeek()) from $totalMinutes`

Q2: The following soft constraints from the manual are already implemented
These are implemented as hard:
- Unwanted patterns ("Break between non-consecutive shifts is at least 10 hours")
- Consecutive working days ("No more than 2 consecutive shifts")
- Alternative skill ("Required skill for a shift")
- Maximum assignments (*technically, minutes of work) ("Weekly minutes must not exceed contract maximum")

These are implemented as soft:
- Day on request ("Desired time slot for an employee")
- Day off request ("Undesired time slot for an employee")

The other constraints vary between hospitals and are not applicable to all employee rostering use cases. We might add them if they are popular enough.

Q3: Hard constraints can be broken. If they are, this usually mean one of two thing:

. It is impossible to satisfy all hard constraints for the given problem instance.
. You terminated the solver too quickly.

a) Is probably caused by terminating the solver too quickly; try increasing solving time.
b) ...How? That seem like a bug; what is your planning variable? In OptaWeb Employee Rostering, the planning variable is the employee of the shift, so it is literally impossible for a shift to have two employees.

Q4:
a) https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/resources/org/optaweb/employeerostering/service/solver/employeeRosteringScoreRules.drl#L96-L111 and https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java#L143-L154 would be of interest

b) https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/solver/EmployeeRosteringConstraintProvider.java#L188-L201 and https://github.com/kiegroup/optaweb-employee-rostering/blob/e206cb73412544a1920792e84625029c95a0a46e/optaweb-employee-rostering-backend/src/main/resources/org/optaweb/employeerostering/service/solver/employeeRosteringScoreRules.drl#L150-L167 would be of interest (you need to change the groupBy/accumlate to count the number of shifts on the weekend instead of the total minutes worked.

Hoped this helps

**Comment by YQ-Xiong** [comment] 2020-12-11 18:40
Hello @Christopher-Chianelli ,
     I am writing a web app with optaplanner. My use case would also need minimum minutes constraints. I went with your suggestions above, but there are some problems. Here is the code I wrote for minimum minutes per day. 
```Java
    Constraint dailyMinutesMustNotBelowContractMinimum(ConstraintFactory constraintFactory) {
        return constraintFactory.from(Employee.class)
                .filter(employee -> employee.getContract().getMinimumMinutesPerDay() != null)
                .join(Shift.class, equal(Function.identity(), Shift::getEmployee))
                .groupBy((employee, shift) -> employee,
                        (employee, shift) -> shift.getStartDateTime().toLocalDate(),
                        sumDuration((employee, shift) ->
                                between(shift.getStartDateTime(), shift.getEndDateTime())))
                .filter((employee, firstDayOfWeek, totalWorkingTime) ->
                        totalWorkingTime.toMinutes() < employee.getContract().getMinimumMinutesPerDay())
                .penalizeConfigurableLong(CONSTRAINT_DAILY_MINUTES_MUST_NOT_BELOW_CONTRACT_MINIMUM,
                        (employee, firstDayOfWeek, totalWorkingTime)->
                                employee.getContract().getMinimumMinutesPerDay() - totalWorkingTime.toMinutes());
    }
```
Which should be the same as what you suggested. But I found that if employees are not assigned with any shift, the constraint would not be matched.

After ```.join``` below
```java
.join(Shift.class, equal(Function.identity(), Shift::getEmployee))
```
If some employees are not assigned with any shift, these employees will be filtered out. As a result, there are no constraint matches for them. However, they are supposed to have constraint matches since these employees do not satisfy minimum minutes constraint(total working minutes  = 0). 

How should I approach this problem, if I want to have a minimum minutes per day constraint which will match even if employees are not assigned with any shift?

**Comment by Christopher-Chianelli** [comment] 2020-12-11 19:08
@YQ-Xiong I know this problem; in short, it occurs because groupBy doesn't trigger if there isn't any tuples in the stream to begin with. There is a workaround though: split it into two constraints: one for when the Employee is assigned to at least one shift, and one when the Employee is assigned to no shifts.

The one where employee is assigned to no Shifts look like this
```
    Constraint dailyMinutesMustNotBelowContractMinimumNoShifts(ConstraintFactory constraintFactory) {
        return constraintFactory.from(Employee.class)
                .filter(employee -> employee.getContract().getMinimumMinutesPerDay() != null)
                .ifNotExists(Shift.class, equal(Function.identity(), Shift::getEmployee))
.penalizeConfigurableLong(CONSTRAINT_DAILY_MINUTES_MUST_NOT_BELOW_CONTRACT_MINIMUM,
                        (employee)->
                                employee.getContract().getMinimumMinutesPerDay());
    }
```

Another alternative is to use a shadow variable that keep track of hours worked, which would be more performant, but has a higher maintenance cost.

Ideally, in the future we'll have some way to perform an accumulate with a default value in Constraint Stream.

**Comment by YQ-Xiong** [comment] 2020-12-11 20:07
@Christopher-Chianelli , thanks for your quick reply. Your answer helps me a lot.
As for splitting the the constraint into two. I can see that it work. However:
1. Is there a way to know which day the employee violates minimum minutes per day constraint (for the one assigned to no shifts)? 
2. If an employee violates this constraint multiple days(not assigned in multiple days), is it possible for us to have multiple constraint matches?

**Comment by Christopher-Chianelli** [comment] 2020-12-11 20:14
@YQ-Xiong 

1. Yes; dailyMinutesMustNotBelowContractMinimumNoShifts written in the above way, will trigger precisely for the employees who have no shifts, and not for any other employees. You can use the Constraint Match Total or Indictment API to find these employees (https://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html#usingScoreCalculationOutsideTheSolver).

2. You would need to join on something like Timeslot, followed by `ifNotExists`:

```
   Constraint dailyMinutesMustNotBelowContractMinimumNoShifts(ConstraintFactory constraintFactory) {
        return constraintFactory.from(Employee.class)
                .filter(employee -> employee.getContract().getMinimumMinutesPerDay() != null)
                .join(Day.class)
                .ifNotExists(Shift.class, equal(Function.identity(), Shift::getEmployee), Joiners.equal((e, day) -> day, Shift::getDay))
.penalizeConfigurableLong(CONSTRAINT_DAILY_MINUTES_MUST_NOT_BELOW_CONTRACT_MINIMUM,
                        (employee, day)->
                                employee.getContract().getMinimumMinutesPerDay());
    }
```
which would trigger exactly once per employee/day pair (you would also need the corresponding hasAtLeastOneShift case)

**Comment by YQ-Xiong** [comment] 2020-12-14 23:34
@Christopher-Chianelli 
Thank you! I got it working with your help.

The first joiner should be modified to the code below since we join Day.class right?
```java
equal((e, day) -> e, Shift::getEmployee)
```

**Comment by Christopher-Chianelli** [comment] 2020-12-15 05:36
@YQ-Xiong You are referring to the joiner in the `ifNotExists`, right? In that case, you are correct, and it should look like
```
.ifNotExists(Shift.class, equal((e, day) -> e, Shift::getEmployee), Joiners.equal((e, day) -> day, Shift::getDay))
```
Good catch!

**Comment by miyamoza** [comment] 2021-02-13 14:37
@Christopher-Chianelli 

will this minimum minutes constraint be part of the main branch?

**Closed** 2022-07-21 09:56 UTC
