### ISSUE TITLE
Delete object request is not working

### ISSUE THREAD

**Issue by lacroixca** [kiegroup/optaweb-employee-rostering#73] opened 2018-03-04 08:35 UTC
Every time I try to delete a worker, skill, shift, etc. I get an error (see photo). Why is this?

![optashift02](https://user-images.githubusercontent.com/1235235/36943771-e3a8a572-1f5c-11e8-873d-e8ae083dcb49.jpg)

**Comment by ge0ffrey** [comment] 2018-03-29 09:41
Probably becuase it's used somewhere and there's a foreign key violation. The UI needs to display this better.

**Comment by FaisalDefry** [comment] 2018-05-23 17:23
hello, is this confirmed as a bug?

**Comment by Christopher-Chianelli** [comment] 2019-11-29 15:46
Closing since the UI now informs the user of the foreign key violation and explains how to fix it

**Closed by Christopher-Chianelli** 2019-11-29 15:46 UTC
Labels: bug
